version: "3"
services:
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
            args:
                TZ: ${TZ-Asia/Shanghai}
        network_mode: "host"
        restart: always
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        volumes:
            - /opt/docker-mcsm/releases/daemon/data:/opt/docker-mcsm/releases/daemon/data
            - /opt/docker-mcsm/releases/daemon/logs:/opt/docker-mcsm/releases/daemon/logs
            - /var/run/docker.sock:/var/run/docker.sock:ro
